version: '3'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2182:2182
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper/0.0.0.0:2182
  mysql:
    image: mysql
    build:
      context: ./
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    container_name: flask_db
  flask:
    build:
      context: ./
    ports:
      - 3200:3200
    container_name: flask_app
    depends_on:
      - mysql
networks:
    default:
        external:
          name:
            app-network
